export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ID_DETAIL_PRODUCTS = "GET_ID_DETAIL_PRODUCTS";
export const SET_PAGE = "SET_PAGE";
export const PRODUCTS_PER_PAGE = "PRODUCTS_PER_PAGE";
export const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const USER_BY_ID = "USER_BY_ID";
export const FILT_BY_CATEGORY = "FILT_BY_CATEGORY";
export const POST_PRODUCT = "POST_PRODUCT";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const POST_CATEGORY = "POST_CATEGORY";
export const FILT_BY_COLOR = "FILT_BY_COLOR";
export const FILT_BY_SIZE = "FILT_BY_SIZE";
export const SET_NAME = "SET_NAME";
export const SAVE_FILTERS = "SAVE_FILTERS";
export const AUTH_USER = "AUTH_USER";
export const ADDING_PRODUCT = "ADDING_PRODUCT"
export const GET_ALL_USERS = "GET_ALL_USERS";
export const BAN_USER = "BAN_USER";
export const UPDATE_USER = "UPDATE_USER";

//GET_OFFERS
//CREATE_PRODUCT
//EDI_PRODUCT
//DELETE_PRODUCT
//CLEAN OBJECT
//CLEAN_STRING
//IS_TRUE
//IS_FALSE
//SUCCES_RESPONSE
//ERROR_RESPONSE
