//products
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ID_DETAIL_PRODUCTS = "GET_ID_DETAIL_PRODUCTS";
export const SET_PAGE = "SET_PAGE";
export const PRODUCTS_PER_PAGE = "PRODUCTS_PER_PAGE";
export const POST_PRODUCT = "POST_PRODUCT";
export const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
export const SET_NAME = "SET_NAME";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

//FILTER
export const GET_CATEGORIES = "GET_CATEGORIES";
export const POST_CATEGORY = "POST_CATEGORY";
export const FILT_BY_CATEGORY = "FILT_BY_CATEGORY";
export const FILT_BY_COLOR = "FILT_BY_COLOR";
export const FILT_BY_SIZE = "FILT_BY_SIZE";
export const SAVE_FILTERS = "SAVE_FILTERS";

//PURCHASE
export const GET_PURCHASES = "GET_PURCHASES";
export const POST_PURCHASE = "POST_PURCHASE";

//CART
export const GET_CART = "GET_CART";
export const CLEAN_CART = "CLEAR_CART";
export const ADDING_PRODUCT = "ADDING_PRODUCT";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY"
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY"
export const REMOVING_PRODUCT = "REMOVING_PRODUCT"
export const CLEAN_CART_REDUCER = "CLEAN_CART_REDUCER"

//CHECKOUT
export const SHIPPING_TYPE = "SHIPPING_TYPE"
export const SHIPPING_COST = "SHIPPING_COST"
//SUCCES_RESPONSE
//ERROR_RESPONSE

//USER
export const AUTH_USER = "AUTH_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const USER_BY_ID = "USER_BY_ID";
export const BAN_USER = "BAN_USER";
export const UPDATE_USER = "UPDATE_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const SAVE_EMAIL = "SAVE_EMAIL";

//OFFERS
export const GET_OFFERS = "GET_OFFERS";

//ORDERS
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERID = "GET_ORDERID";
export const PUT_ORDER = "PUT_ORDER";
//FAVORITOS
export const GET_FAVORITES_BY_ID_USER = "GET_FAVORITES_BY_ID_USER" 
export const ADD_FAVS = "ADD_FAVS"
export const DELETE_FAV = "DELETE_FAV" 

//REVIEWS
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS";
export const GET_REVIEW_BY_USERID = "GET_REVIEW_BY_USERID";
export const POST_REVIEW = "POST_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";

//GET_OFFERS
//CREATE_PRODUCT
//EDI_PRODUCT
//DELETE_PRODUCT
//CLEAN OBJECT
//CLEAN_STRING
//IS_TRUE
//IS_FALSE
