export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ID_DETAIL_PRODUCTS = "GET_ID_DETAIL_PRODUCTS";
//GET_PRODUCT_DETAIL
export const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
//NAME
//GET_OFFERS
//CREATE_PRODUCT
//EDI_PRODUCT
//DELETE_PRODUCT
//CLEAN OBJECT
//CLEAN_STRING
//IS_TRUE
//IS_FALSE
//SUCCES_RESPONSE
//ERROR_RESPONSE
